package com.example.group7.Wsdl2Code.OnlineIntegrationService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/31/2016 1:56:47 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.example.group7.Wsdl2Code.OnlineIntegrationService.debtTO;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class addNewDebtResponsee implements KvmSerializable {

    public debtTO debt;
    public double newAmount;
    public boolean newAmountSpecified;
    public String message;
    public int returnCodeField;
    
    public addNewDebtResponsee(){}
    
    public addNewDebtResponsee(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("debt"))
        {
            debt = new debtTO(soapObject);
        }
        if (soapObject.hasProperty("newAmount"))
        {
            Object obj = soapObject.getProperty("newAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                newAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                newAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("newAmountSpecified"))
        {
            Object obj = soapObject.getProperty("newAmountSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                newAmountSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                newAmountSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("message"))
        {
            Object obj = soapObject.getProperty("message");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                message = j.toString();
            }else if (obj!= null && obj instanceof String){
                message = (String) obj;
            }
        }
        if (soapObject.hasProperty("returnCode"))
        {
            Object obj = soapObject.getProperty("returnCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                returnCodeField = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                returnCodeField = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return newAmount;
            case 1:
                return newAmountSpecified;
            case 2:
                return message;
            case 3:
                return returnCodeField;
            case 4:
                return debt;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 5;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = Double.class;
                info.name = "newAmount";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "newAmountSpecified";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "message";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "returnCode";
                break;
            case 4:
                info.type = debtTO.class;
                info.name = "debt";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
